//
#ifndef __BB_DEV_MGR_ERRORS_H__
#define __BB_DEV_MGR_ERRORS_H__

#include <winerror.h>


/* IDevice codes */
#define ICHANNEL_OPEN_NAK_RESERVED                  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 0)
#define ICHANNEL_OPEN_NAK_NOT_SUPPORTED             MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 1)
#define ICHANNEL_OPEN_NAK_ALREADY_OPEN              MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 2)
#define ICHANNEL_OPEN_NAK_MAX_CHANNELS_EXCEEDED     MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 3)
#define ICHANNEL_OPEN_NAK_REJECTED_BY_APPLICATION   MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 4)
#define ICHANNEL_OPEN_NAK_BOOTROM_INTERNAL          MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 5)
#define ICHANNEL_OPEN_NAK_WAIT_TIMEOUT              MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 6)
#define ICHANNEL_OPEN_NAK_INVALID_PARAMETER         MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 7)
#define ICHANNEL_TERM_ACK_RECEIVED                  MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 8)
#define DEVOBJ_PIPE_CLOSED                          MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, 9)

//Use a new class of error codes - the above conflict with normal win/ole errors
#define IDEVICE_INVALID                             MAKE_HRESULT(SEVERITY_ERROR, 5, 10)
#define IDEVICE_HUB_ADDR_FAILED                     MAKE_HRESULT(SEVERITY_ERROR, 5, 11)
#define IDEVICE_NOT_SUPPORTED                       MAKE_HRESULT(SEVERITY_ERROR, 5, 12)

/* NOTE: Next error code should start with 220h to minimize any confusion with
 *       Windows COM error codes already defined in WINERROR.H */


#endif 

